ALTER TABLE complaints ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS district VARCHAR(100);
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS assigned_technician_id BIGINT;
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS assigned_by_user_id BIGINT;
