spring.application.name=tenant-provisioning-service
server.port=8086

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/epsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=tenant-provisioning-service
spring.kafka.consumer.auto-offset-reset=earliest
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.com.eps=DEBUG
