spring.application.name=geography-service
server.port=8087

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/epsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration

grpc.server.port=9087
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.com.eps=DEBUG
