spring.application.name=analytics-service
server.port=8083
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/epsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=analytics-service-group
spring.kafka.consumer.auto-offset-reset=earliest
logging.level.root=INFO
logging.level.com.eps=DEBUG
