spring.application.name=payment-service
server.port=8093
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/epsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.properties.hibernate.multi_tenant_connection_provider=com.eps.shared.tenant.SchemaBasedMultiTenantConnectionProvider
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.eps.shared.tenant.TenantIdentifierResolver
spring.flyway.enabled=false
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
billing-service.url=${BILLING_SERVICE_URL:http://localhost:8090}
logging.level.root=INFO
logging.level.com.eps=DEBUG
