spring.application.name=connection-service
server.port=8095

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/epsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.properties.hibernate.multi_tenant_connection_provider=com.eps.shared.tenant.SchemaBasedMultiTenantConnectionProvider
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.eps.shared.tenant.TenantIdentifierResolver
spring.flyway.enabled=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

payment-service.url=${PAYMENT_SERVICE_URL:http://localhost:8093}

logging.level.root=INFO
logging.level.com.eps=DEBUG
