spring.application.name=api-gateway
server.port=4004

jwt.secret=mySecretKeyForElectricityDistributionPlatformThatIsLongEnoughForHS256Algorithm

# Logging
logging.level.root=INFO
logging.level.com.eps=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
